import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Auth with NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={"jumbotron text-center bg-primary"}>Auth with NextJS</h1>
      </main>
    </div>
  );
};

export default Home;
